project_id = "qpsldrtvzarqlzrdoirl"

[functions.product-ai]
verify_jwt = false

[extensions.pg_net]
version = "*"
schema = "extensions"

[app.settings]
supabase_url = "https://qpsldrtvzarqlzrdoirl.supabase.co"
service_role_key = "YOUR_SERVICE_ROLE_KEY"
